# Generated by Django 5.2.1 on 2025-08-05 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_productcategory_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
